# Generated by Django 5.0.7 on 2024-08-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcskid",
                    models.CharField(
                        blank=True, default="", max_length=10, unique=True
                    ),
                ),
                ("fcname", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcskid",
                    models.CharField(
                        blank=True, default="", max_length=10, unique=True
                    ),
                ),
                ("fcname", models.CharField(blank=True, default="", max_length=100)),
                (
                    "fccorp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="company_department.company",
                    ),
                ),
            ],
        ),
    ]
