# Generated by Django 5.1 on 2024-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_department", "0002_company_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="line_notify_car",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="line_notify_room",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
