# Generated by Django 5.1.1 on 2024-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_department', '0003_company_line_notify_car_company_line_notify_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fcskid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='fcskid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
