# Generated by Django 5.0.7 on 2024-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0003_booking_color_alter_booking_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
