# Generated by Django 5.0.7 on 2024-08-09 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0004_alter_booking_end_date_alter_booking_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("color", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="booking",
            name="color",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="flag",
            new_name="remark",
        ),
        migrations.AddField(
            model_name="booking",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="booking",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="room.status",
            ),
        ),
        migrations.DeleteModel(
            name="color",
        ),
    ]
