# Generated by Django 5.0.7 on 2024-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_status_remove_booking_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="sequence",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
