# Generated by Django 5.0.4 on 2024-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0012_alter_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="sequence",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
