# Generated by Django 5.1 on 2024-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0013_room_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="remark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
