# Generated by Django 5.1 on 2024-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0014_room_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
    ]
