# Generated by Django 5.1 on 2024-08-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0015_alter_room_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
    ]
