# Generated by Django 5.1 on 2024-08-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0016_alter_booking_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="room.room_status",
            ),
        ),
    ]
