# Generated by Django 5.1.1 on 2024-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0017_room_status_alter_room_sequence_room_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="message",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
