# Generated by Django 5.1.1 on 2024-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_room_maximum_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
