# Generated by Django 5.1 on 2024-08-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_location_booking_location"),
        ("company_department", "0002_company_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="car_bookings",
                to="company_department.company",
            ),
        ),
    ]
