# Generated by Django 5.1 on 2024-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tel",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
